== String Operations

Estimated time needed: *15* minutes

=== Objectives

After completing this lab you will be able to:

* Work with Strings
* Perform operations on String
* Manipulate Strings using indexing and escape sequences

Table of Contents

....
<ul>
    <li>
        <a href="https://#strings">What are Strings?</a>
    </li>
    <li>
        <a href="https://#index">Indexing</a>
        <ul>
            <li><a href="https://neg/?utm_medium=Exinfluencer&utm_source=Exinfluencer&utm_content=000026UJ&utm_term=10006555&utm_id=NA-SkillsNetwork-Channel-SkillsNetworkCoursesIBMDeveloperSkillsNetworkPY0101ENSkillsNetwork19487395-2021-01-01">Negative Indexing</a></li>
            <li><a href="https://slice/?utm_medium=Exinfluencer&utm_source=Exinfluencer&utm_content=000026UJ&utm_term=10006555&utm_id=NA-SkillsNetwork-Channel-SkillsNetworkCoursesIBMDeveloperSkillsNetworkPY0101ENSkillsNetwork19487395-2021-01-01">Slicing</a></li>
            <li><a href="https://stride/?utm_medium=Exinfluencer&utm_source=Exinfluencer&utm_content=000026UJ&utm_term=10006555&utm_id=NA-SkillsNetwork-Channel-SkillsNetworkCoursesIBMDeveloperSkillsNetworkPY0101ENSkillsNetwork19487395-2021-01-01">Stride</a></li>
            <li><a href="https://concat/?utm_medium=Exinfluencer&utm_source=Exinfluencer&utm_content=000026UJ&utm_term=10006555&utm_id=NA-SkillsNetwork-Channel-SkillsNetworkCoursesIBMDeveloperSkillsNetworkPY0101ENSkillsNetwork19487395-2021-01-01">Concatenate Strings</a></li>
        </ul>
    </li>
    <li>
        <a href="https://#escape">Escape Sequences</a>
    </li>
    <li>
        <a href="https://#operations">String Operations</a>
    </li>
    <li>
        <a href="https://#quiz">Quiz on Strings</a>
    </li>
</ul>
....

What are Strings?

The following example shows a string contained within 2 quotation marks:


+*In[1]:*+
[source, ipython3]
----
# Use quotation marks for defining string

"Michael Jackson"
----


+*Out[1]:*+
----'Michael Jackson'----

We can also use single quotation marks:


+*In[2]:*+
[source, ipython3]
----
# Use single quotation marks for defining string

'Michael Jackson'
----


+*Out[2]:*+
----'Michael Jackson'----

A string can be a combination of spaces and digits:


+*In[3]:*+
[source, ipython3]
----
# Digitals and spaces in string

'1 2 3 4 5 6 '
----


+*Out[3]:*+
----'1 2 3 4 5 6 '----

A string can also be a combination of special characters :


+*In[4]:*+
[source, ipython3]
----
# Special characters in string

'@#2_#]&*^%$'
----


+*Out[4]:*+
----'@#2_#]&*^%$'----

We can print our string using the print statement:


+*In[5]:*+
[source, ipython3]
----
# Print the string

print("hello!")
----


+*Out[5]:*+
----
hello!
----

We can bind or assign a string to another variable:


+*In[6]:*+
[source, ipython3]
----
# Assign string to variable

name = "Michael Jackson"
name
----


+*Out[6]:*+
----'Michael Jackson'----



Indexing

It is helpful to think of a string as an ordered sequence. Each element
in the sequence can be accessed using an index represented by the array
of numbers:



The first index can be accessed as follows:




+*In[7]:*+
[source, ipython3]
----
# Print the first element in the string

print(name[0])
----


+*Out[7]:*+
----
M
----

We can access index 6:


+*In[8]:*+
[source, ipython3]
----
# Print the element on index 6 in the string

print(name[6])
----


+*Out[8]:*+
----
l
----

Moreover, we can access the 13th index:


+*In[9]:*+
[source, ipython3]
----
# Print the element on the 13th index in the string

print(name[13])
----


+*Out[9]:*+
----
o
----

Negative Indexing

We can also use negative indexing with strings:



Negative index can help us to count the element from the end of the
string.

The last element is given by the index -1:


+*In[10]:*+
[source, ipython3]
----
# Print the last element in the string

print(name[-1])
----


+*Out[10]:*+
----
n
----

The first element can be obtained by index -15:


+*In[11]:*+
[source, ipython3]
----
# Print the first element in the string

print(name[-15])
----


+*Out[11]:*+
----
M
----

We can find the number of characters in a string by using len, short for
length:


+*In[12]:*+
[source, ipython3]
----
# Find the length of string

len("Michael Jackson")
----


+*Out[12]:*+
----15----

Slicing

We can obtain multiple characters from a string using slicing, we can
obtain the 0 to 4th and 8th to the 12th element:



[Tip]: When taking the slice, the first number means the index (start at
0), and the second number means the length from the index to the last
element you want (start at 1)


+*In[13]:*+
[source, ipython3]
----
# Take the slice on variable name with only index 0 to index 3

name[0:4]
----


+*Out[13]:*+
----'Mich'----


+*In[14]:*+
[source, ipython3]
----
# Take the slice on variable name with only index 8 to index 11

name[8:12]
----


+*Out[14]:*+
----'Jack'----

Stride

We can also input a stride value as follows, with the `2' indicating
that we are selecting every second variable:




+*In[15]:*+
[source, ipython3]
----
# Get every second element. The elments on index 1, 3, 5 ...

name[::2]
----


+*Out[15]:*+
----'McalJcsn'----

We can also incorporate slicing with the stride. In this case, we select
the first five elements and then use the stride:


+*In[16]:*+
[source, ipython3]
----
# Get every second element in the range from index 0 to index 4

name[0:5:2]
----


+*Out[16]:*+
----'Mca'----

Concatenate Strings

We can concatenate or combine strings by using the addition symbols, and
the result is a new string that is a combination of both:


+*In[17]:*+
[source, ipython3]
----
# Concatenate two strings

statement = name + "is the best"
statement
----


+*Out[17]:*+
----'Michael Jacksonis the best'----

To replicate values of a string we simply multiply the string by the
number of times we would like to replicate it. In this case, the number
is three. The result is a new string, and this new string consists of
three copies of the original string:


+*In[18]:*+
[source, ipython3]
----
# Print the string for 3 times

3 * "Michael Jackson"
----


+*Out[18]:*+
----'Michael JacksonMichael JacksonMichael Jackson'----

You can create a new string by setting it to the original variable.
Concatenated with a new string, the result is a new string that changes
from Michael Jackson to ``Michael Jackson is the best''.


+*In[19]:*+
[source, ipython3]
----
# Concatenate strings

name = "Michael Jackson"
name = name + " is the best"
name
----


+*Out[19]:*+
----'Michael Jackson is the best'----



Escape Sequences

Back slashes represent the beginning of escape sequences. Escape
sequences represent strings that may be difficult to input. For example,
back slash ``n'' represents a new line. The output is given by a new
line after the back slash ``n'' is encountered:


+*In[20]:*+
[source, ipython3]
----
# New line escape sequence

print(" Michael Jackson \n is the best" )
----


+*Out[20]:*+
----
 Michael Jackson 
 is the best
----

Similarly, back slash ``t'' represents a tab:


+*In[21]:*+
[source, ipython3]
----
# Tab escape sequence

print(" Michael Jackson \t is the best" )
----


+*Out[21]:*+
----
 Michael Jackson 	 is the best
----

If you want to place a back slash in your string, use a double back
slash:


+*In[22]:*+
[source, ipython3]
----
# Include back slash in string

print(" Michael Jackson \\ is the best" )
----


+*Out[22]:*+
----
 Michael Jackson \ is the best
----

We can also place an ``r'' before the string to display the backslash:


+*In[24]:*+
[source, ipython3]
----
# r will tell python that string will be display as raw string

print(r" Michael Jackson \ is the best")
----


+*Out[24]:*+
----
 Michael Jackson \ is the best
----



String Operations

There are many string operation methods in Python that can be used to
manipulate the data. We are going to use some basic string operations on
the data.

Let’s try with the method upper; this method converts lower case
characters to upper case characters:


+*In[25]:*+
[source, ipython3]
----
# Convert all the characters in string to upper case

a = "Thriller is the sixth studio album"
print("before upper:", a)
b = a.upper()
print("After upper:", b)
----


+*Out[25]:*+
----
before upper: Thriller is the sixth studio album
After upper: THRILLER IS THE SIXTH STUDIO ALBUM
----

The method replace replaces a segment of the string, i.e. a substring
with a new string. We input the part of the string we would like to
change. The second argument is what we would like to exchange the
segment with, and the result is a new string with the segment changed:


+*In[26]:*+
[source, ipython3]
----
# Replace the old substring with the new target substring is the segment has been found in the string

a = "Michael Jackson is the best"
b = a.replace('Michael', 'Janet')
b
----


+*Out[26]:*+
----'Janet Jackson is the best'----

The method find finds a sub-string. The argument is the substring you
would like to find, and the output is the first index of the sequence.
We can find the sub-string jack or el.




+*In[27]:*+
[source, ipython3]
----
# Find the substring in the string. Only the index of the first elment of substring in string will be the output

name = "Michael Jackson"
name.find('el')
----


+*Out[27]:*+
----5----


+*In[28]:*+
[source, ipython3]
----
# Find the substring in the string.

name.find('Jack')
----


+*Out[28]:*+
----8----

If the sub-string is not in the string then the output is a negative
one. For example, the string `Jasdfasdasdf' is not a substring:


+*In[29]:*+
[source, ipython3]
----
# If cannot find the substring in the string

name.find('Jasdfasdasdf')
----


+*Out[29]:*+
-----1----



Quiz on Strings

What is the value of the variable a after the following code is
executed?


+*In[30]:*+
[source, ipython3]
----
# Write your code below and press Shift+Enter to execute 

a = "1"
----

Click here for the solution

[source,python]
----
"1"
----

What is the value of the variable b after the following code is
executed?


+*In[31]:*+
[source, ipython3]
----
# Write your code below and press Shift+Enter to execute

b = "2"
----

Click here for the solution

[source,python]
----
"2"
----

What is the value of the variable c after the following code is
executed?


+*In[34]:*+
[source, ipython3]
----
# Write your code below and press Shift+Enter to execute 

c = a + b

----

Click here for the solution

[source,python]
----
"12"
----



Consider the variable d use slicing to print out the first three
elements:


+*In[35]:*+
[source, ipython3]
----
# Write your code below and press Shift+Enter to execute

d = "ABCDEFG"
print(d[:3])
----


+*Out[35]:*+
----
ABC
----

Click here for the solution

[source,python]
----
print(d[:3]) 

# or 

print(d[0:3])
----



Use a stride value of 2 to print out every second character of the
string e:


+*In[36]:*+
[source, ipython3]
----
# Write your code below and press Shift+Enter to execute

e = 'clocrkr1e1c1t'
print(e[::2])
----


+*Out[36]:*+
----
correct
----

Click here for the solution

[source,python]
----
print(e[::2])
----



Print out a backslash:


+*In[39]:*+
[source, ipython3]
----
# Write your code below and press Shift+Enter to execute
print(r"\ ")

----


+*Out[39]:*+
----
\ 
----

Click here for the solution

[source,python]
----
print("\\\\")

or

print(r"\ ")
----



Convert the variable f to uppercase:


+*In[40]:*+
[source, ipython3]
----
# Write your code below and press Shift+Enter to execute

f = "You are wrong"
f.upper()
----


+*Out[40]:*+
----'YOU ARE WRONG'----

Click here for the solution

[source,python]
----
f.upper()
----



Consider the variable g, and find the first index of the sub-string
snow:


+*In[41]:*+
[source, ipython3]
----
# Write your code below and press Shift+Enter to execute

g = "Mary had a little lamb Little lamb, little lamb Mary had a little lamb \
Its fleece was white as snow And everywhere that Mary went Mary went, Mary went \
Everywhere that Mary went The lamb was sure to go"
g.find("snow")
----


+*Out[41]:*+
----95----

Click here for the solution

[source,python]
----
g.find("snow")
----

In the variable g, replace the sub-string Mary with Bob:


+*In[48]:*+
[source, ipython3]
----
# Write your code below and press Shift+Enter to execute
g.replace("Mary","Bob")

----


+*Out[48]:*+
----'Bob had a little lamb Little lamb, little lamb Bob had a little lamb Its fleece was white as snow And everywhere that Bob went Bob went, Bob went Everywhere that Bob went The lamb was sure to go'----

Click here for the solution

[source,python]
----
g.replace("Mary", "Bob")
----

The last exercise!

Congratulations, you have completed your first lesson and hands-on lab
in Python. However, there is one more thing you need to do. The Data
Science community encourages sharing work. The best way to share and
showcase your work is to share it on GitHub. By sharing your notebook on
GitHub you are not only building your reputation with fellow data
scientists, but you can also show it off when applying for a job. Even
though this was your first piece of work, it is never too early to start
building good habits. So, please read and follow this article to learn
how to share your work.

== Author

Joseph Santarcangelo

== Change Log

[cols=",,,",options="header",]
|===
|Date (YYYY-MM-DD) |Version |Changed By |Change Description
|2020-11-11 |2.1 |Aije |Updated variable names to lowercase
|2020-08-26 |2.0 |Lavanya |Moved lab to course repo in GitLab
|===

##

© IBM Corporation 2020. All rights reserved.
